server.port=8888
spring.application.name=config-tool

# Disable Thymeleaf caching
spring.thymeleaf.cache=false

# Serve static files from React build
spring.web.resources.static-locations=classpath:/static/,classpath:/META-INF/resources/,file:src/main/frontend/dist/
spring.mvc.static-path-pattern=/**
spring.web.index-view-name=forward:/index.html